name: 'my_project'
version: '1.0'
profile: 'my_project'  # This should match the profile name from your profiles.yml
source-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
