
my_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: timescale   # Service name as per docker-compose.yml
      user: postgres
      password: mypassword
      dbname: jobsdb
      schema: public
      port: 5434







