version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "39931:39931"
    volumes:
      - my-dev-stack_minio_data:/data
    command: server /data

  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    ports:
      - "5434:5434"
    volumes:
      - my-dev-stack_timescale_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "4000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  my-dev-stack_minio_data:
  my-dev-stack_timescale_data:
  grafana_data:
