name: Dev Environment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-dev-environment:
    name: Setup Dev Environment
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Set up Docker Compose (ensure it's installed)
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Step 4: Start Services with Docker Compose
    - name: Start Services with Docker Compose
      run: |
        docker-compose up -d
        docker ps

    # Step 5: Verify Running Services
    - name: Verify Running Services
      run: |
        docker logs timescaledb
        docker logs minio
    # Step 6: Add charts folder to GitHub
    - name: Create charts folder if it doesn't exist
  run: |
    mkdir -p charts

     - name: Commit and push charts folder to GitHub
  run: |
    git config --global user.name "harishini"
    git config --global user.email "devaharishini@gmail.com"
    git add charts/
    git commit -m "Add charts folder"
    git push origin main


