name: Dev Environment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-dev-environment:
    name: Setup Dev Environment
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build and Start Services
    - name: Start Services with Docker Compose
      run: |
        docker-compose up -d
        docker ps

    # Step 4: Verify Services are Running
    - name: Verify Running Services
      run: |
        docker logs timescaledb
        docker logs minio
