name: Build Development Environment

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu environment

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (required for Docker builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build DBT Docker image from the Dockerfile in the dbt folder
      - name: Build DBT Docker image
        run: |
          docker build -t my-dbt-image ./dbt

      # Step 4: Start Docker Compose services (optional, e.g., TimescaleDB)
      - name: Start Docker Compose services
        run: |
          docker-compose -f docker-compose.yml up -d

      # Step 5: Run DBT models (run the DBT image to process data models)
      - name: Run DBT models
        run: |
          docker run --rm my-dbt-image dbt run

      # Step 6: (Optional) Run DBT tests
      - name: Run DBT tests
        run: |
          docker run --rm my-dbt-image dbt test
