name: Dev Environment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-dev-environment:
    name: Setup Dev Environment
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.30.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verify installation

    # Step 4: Start Services with Docker Compose
    - name: Start Services with Docker Compose
      run: |
        docker-compose up -d
        docker ps  # List running containers

    # Step 5: Verify Running Services
    - name: Verify Running Services
      run: |
        docker logs timescaledb  # Logs for timescaledb container
        docker logs minio         # Logs for minio container

    # Step 6: Create charts folder and subfolders
    - name: Create charts folder structure
      run: |
        mkdir -p charts/keycloak charts/grafana charts/minio charts/argo
        touch charts/.keep

    # Step 7: Commit and push charts folder
    - name: Commit and Push charts folder
      run: |
        git config --global user.name "harishini"
        git config --global user.email "harishinikp@gmail.com"
        git add charts/
        git commit -m "Add charts folder structure"
        git push origin main
      continue-on-error: true

