name: Build Development Environment

on:
  push:
    branches:
      - master  # Ensure it listens for pushes to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t my-dbt-image -f dbt/Dockerfile .

      - name: Start Docker Compose services
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run DBT models
        run: |
          docker run --rm my-dbt-image dbt run
